- name: Service and Pod deployment
  hosts: all
  user: parallels
#  become: true
  tasks: 
    #  - name: delete old deployment
    #    command: kubectl delete -f /home/ubuntu/Deployment.yml
    #  - name: delete old service
    #    command: kubectl delete -f /home/ubuntu/Service.yml
     - name: Copy files from local to remote servers
       copy:
          src: /var/lib/jenkins/workspace/java_app-02/kubernetes
          dest: /home/parallels/
     - name: create new Deployment and Service for Product Catalogue
       command: minikube kubectl -- apply -f /home/parallels/kubernetes/productcatalogue-service.yml
     - name: create new Deployment and Service for Shopfront
       command: minikube kubectl -- apply -f /home/parallels/kubernetes/shopfront-service.yml
     - name: create new Deployment and Service for Stockmanager
       command: minikube kubectl -- apply -f /home/parallels/kubernetes/stockmanager-service.yml
